### ISSUE TITLE
Embedded bashcov

### ISSUE THREAD

**Issue by albfan** [infertux/bashcov#14]
Hi, I'm using bashcov to cover https://github.com/albfan/git-ignore

Problem with git-ignore is it is launched by git when you issue "git ignore". By now I hack this with

https://github.com/albfan/git-ignore/blob/master/t/setup.sh#L7

where COV_PROGRAM is "bashcov --"

That works but would be great to find a way that bashcov replaces /bin/sh to avoid extra config for code coverage.

https://github.com/albfan/git-ignore/blob/master/t/t0001-exclude.sh#L3

something like:

    SHARNESS_TEST_EXTENSION="bashcov"

**Comment by BaxterStockman** [comment]
@albfan , if I understand correctly, you're looking for a way to do something like the following?:

```shell
#!/usr/bin/env bashcov

test_expect_success 'test some stuff, with coverage' '
  echo "Testing, testing, one, two, three"
'
```

If so, you could create a sort of shim for bashcov -- call it `bashcov-shim`:

```shell
#!/usr/bin/env bash 

exec bashcov -- "$@"
```

And then, in your test files, 

```shell
#!/usr/bin/env bashcov-shim

# Testing stuff goes here
```

Would that satisfy your needs?  And, if so -- @infertux, would you want to consider including `bashcov-shim` as part of this gem?

**Comment by BaxterStockman** [comment]
Hah.  So, on a lark, I tried this out:

```shell
#!/usr/bin/env bashcov

echo "WHOA"
```

Guess what:

```shell
user@host /tmp/tmp.EAkRVqyO1A $ ./test.sh
WHOA
Coverage report generated for bashcov v1.3.0 to /tmp/tmp.EAkRVqyO1A/coverage. 1 / 1 LOC (100.0%) covered.
```
Because `bashcov` already passes through arguments after `--` to Bash, it can be used in a shebang line and it will _Just Work_ :tm:.
