### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by golharam** [infertux/bashcov#19]
I just installed bashcov using 'gem install bashcov' and get an error when running 'bashcov --help':

[root@watson golharr]# bashcov --help
/usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': /usr/lib64/ruby/gems/1.8/gems/bashcov-1.3.0/lib/bashcov.rb:17: unknown type of %string (SyntaxError)
    *%i(skip_uncovered mute bash_path root_directory command)
        ^
/usr/lib64/ruby/gems/1.8/gems/bashcov-1.3.0/lib/bashcov.rb:17: syntax error, unexpected $end
    *%i(skip_uncovered mute bash_path root_directory command)
        ^
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib64/ruby/gems/1.8/gems/bashcov-1.3.0/bin/bashcov:7
	from /usr/bin/bashcov:22:in `load'
	from /usr/bin/bashcov:22

**Comment by BaxterStockman** [comment]
Looks like `%i()` was [added in Ruby 2.0](https://github.com/ruby/ruby/commit/91bd6e711db3418baa287e936d4b0fac99927711).  I believe that there are other pre-2.0 incompatibilities (the lowest Ruby version targeted in the Travis build is 2.1.8).  Perhaps `required_ruby_version` should be added to the gemspec?

**Comment by infertux** [comment]
It looks like you're using Ruby 1.8 which is totally obsolete. You should upgrade to [2.0 and even 2.1](https://www.ruby-lang.org/en/downloads/) if you can. What OS / distribution are you using? You should be able to install a newer Ruby version through your package manager.

@BaxterStockman: Yup I think we should add `required_ruby_version` and set it to `>= 2.0.0` to get a friendlier error message than this one.

**Comment by golharam** [comment]
Thanks.  I'll upgrade ruby and try again.
