### ISSUE TITLE
Incorrect coverage report for multiline statements

### ISSUE THREAD

**Issue by infertux** [infertux/bashcov#2]
```bash
variable=($(      
echo hi
))
echo after
```

Reported coverage is `[nil, 0, 1, 2]`. It should be `[nil, 1, 1, 1]`.
This seems to be a bug in Bash?

See the pending spec in `spec/bashcov/runner_spec.rb`.

**Comment by ctubio** [comment]
more examples here: https://coveralls.io/builds/2473076/source?filename=INSTALL

hope it helps! (i know it doesnt xD)

btw, thank you for this lovely *Code coverage tool for Bash*!

**Comment by infertux** [comment]
We could use something like this: https://github.com/albfan/bashcov/commit/09c13450dc26e68f54901fe171cfafcd6d1abe72

**Comment by gbraekmans** [comment]
Any chance this could be merged?

**Comment by infertux** [comment]
Hi @ctubio & @gbraekmans, I just pushed version 1.4.0 to RubyGems.org which has some basic parsing of multiline statements.
