### ISSUE TITLE
bashcov and shUnit2

### ISSUE THREAD

**Issue by golharam** [infertux/bashcov#20]
I'm currently using shunit2 for unit testing my scripts.  Some of my scripts are quite length.  I'd like to use bashcov to generate code coverage data.  When I call bashcov on my unit test script, there a lot of output from bashcov, that I can't see what shunit2 is reporting.  Questions are:
1.  Is there a way to silence bashcov?
2.  Is bashcov compatible with shunit2?  
   2b.  If not, what is the recommend unit testing framework to use with bashcov?

**Comment by BaxterStockman** [comment]
Bashcov has a `--mute` option that silences output from the scripts it executes, as well as some of it's own output.  There is currently no option to disable all output from Bashcov.  However, the `--mute` option might not work for you, since it would likely silense `shunit2`'s own output.

You might be able to get away with redirecting standard error to `/dev/null`, if I'm correct that the Bashcov output you're referring to is stuff like `bashcov: warning: /tmp/shunit.Yh0FXR/noexec was executed but has been deleted since then - it won't be reported in coverage.`.  Would that approach work for you?

(P.S. I like [BATS](https://github.com/sstephenson/bats) for unit testing shell scripts.)

**Comment by infertux** [comment]
Thanks for chiming in @BaxterStockman :)

@golharam: Just to clarify, Bashcov itself only outputs one line on `stdout` normally which is `Coverage report generated for bashcov v1.3.1 to [...]`. It may output additional warnings on `stderr` which look like `bashcov: warning: [...]` if there's a problem.

As @BaxterStockman said, you can silence the output from your script with `bashcov --mute ./your_script.sh`. However I assume you're using `bashcov shunit2 ./your_script.sh`? In this case, you can't silence the output of `your_script.sh` and keep shunit2's output if they're both on `stdout` and/or `stderr`. I'm not familiar with shunit2 but there might be an option to redirect its output to a file?

In any case, you can play around with the `--mute` flag and also redirect `stdout` / `stderr` to `/dev/null` like that: `bashcov ... 2> /dev/null`, `bashcov --mute ... > /dev/null`, etc. and let us know if that helps.

**Comment by golharam** [comment]
Here's some of the output I'm getting:
```

[golharr@watson bashcov_test]$ bashcov ./unitTests.sh
+BASHCOV>46./unitTests.sh/home/golharr/workspace/RNASeq/test/bashcov_test'[' -n '' ']'
+BASHCOV>47./unitTests.sh/home/golharr/workspace/RNASeq/test/bashcov_test. ../shunit2/source/2.1/src/shunit2
++BASHCOV>17../shunit2/source/2.1/src/shunit2/home/golharr/workspace/RNASeq/test/bashcov_test'[' -n '' ']'
++BASHCOV>18../shunit2/source/2.1/src/shunit2/home/golharr/workspace/RNASeq/test/bashcov_testSHUNIT_VERSION=2.1.7pre
++BASHCOV>21../shunit2/source/2.1/src/shunit2/home/golharr/workspace/RNASeq/test/bashcov_testSHUNIT_TRUE=0
++BASHCOV>22../shunit2/source/2.1/src/shunit2/home/golharr/workspace/RNASeq/test/bashcov_testSHUNIT_FALSE=1
++BASHCOV>23../shunit2/source/2.1/src/shunit2/home/golharr/workspace/RNASeq/test/bashcov_testSHUNIT_ERROR=2
```

In this case, I just want to not see the BASHCOV> debug statements.

When I use --mute, I get:

```
[golharr@watson bashcov_test]$ bashcov --mute ./unitTests.sh
bashcov: warning: encountered an error parsing Bash's output (error was: expected integer for LINENO, got `nil'). This can occur if your script or its path contains the sequence "\u001E", or if your script unsets LINENO. Aborting early; coverage report will be incomplete.
Coverage report generated for bashcov v1.3.1 to /home/golharr/workspace/RNASeq/test/bashcov_test/coverage. 0 / 26 LOC (0.0%) covered.

```

I'm not sure what's causing this error.  I don't set/unset LINENO, but not sure if shunit2 does.

**Comment by BaxterStockman** [comment]
@golharam, could you provide a link to your `unitTests.sh` script, or (if that's not available) to another script that encounters the same issue?

Also, what version of Bash are you using, and do you do any manipulation of Bash options in your test suite -- for instance, `set -x`?

**Comment by infertux** [comment]
Ping @golharam

**Comment by infertux** [comment]
It's been nearly two years. Going to close this. Please reopen if this is still happening.
