### ISSUE TITLE
Switch conditions not being reported

### ISSUE THREAD

**Issue by simonewebdesign** [infertux/bashcov#21]
Hi, first of all thanks for this great tool! :)

I noticed case statements don't get reported by simplecov.

For example this simple script:

``` bash
#!/bin/bash

arg=$1

case $arg in
    0)
        echo "arg was 0"
        ;;
    1)
        echo "arg was 1"
        ;;
esac
```

```
bashcov -- ./script.sh 0
bashcov: warning: you are using a version of Bash that does not support BASH_XTRACEFD. All xtrace output will print to standard error, and your script's output on standard error will not be printed to the console.
arg was 0
Coverage report generated for bashcov v1.3.1 to /Users/simone/Projects/bashcov-switch-bug/coverage. 3 / 6 LOC (50.0%) covered.
```

![simplecov](https://cloud.githubusercontent.com/assets/2126073/19122152/1c4de3b4-8b21-11e6-8188-72e0c01e72f5.png)

As you can see, line 6 was missed.

I'm on OS X 10.11.6.

**Comment by infertux** [comment]
Thanks @simonewebdesign, I just pushed version 1.4.0 to RubyGems.org which should fix this issue.

**Comment by simonewebdesign** [comment]
Can confirm it works, just tested. Thanks a lot! :+1:
