### ISSUE TITLE
Doesn't cover multi-line echo

### ISSUE THREAD

**Issue by simonewebdesign** [infertux/bashcov#22]
Hi again :) just another issue I found, please see below.

``` bash
#!/bin/bash

echo 'Usage: frob [options] <path> [options]'

echo 'Examples:'
echo '    frob --stuff /usr/bin'
echo '    frob -f fubar/baz'

echo '
hello
there
'

echo hi
```

![frobnicate](https://cloud.githubusercontent.com/assets/2126073/19219879/49bfc2f6-8e17-11e6-8ab3-393d0a41d0cb.png)

**Comment by infertux** [comment]
Version 1.4.1 has been pushed to RubyGems ;)

**Comment by simonewebdesign** [comment]
Thank you! :)
