### ISSUE TITLE
Issue with multi-line strings

### ISSUE THREAD

**Issue by simonewebdesign** [infertux/bashcov#23]
It's me again, hopefully the last issue!

``` bash
#!/bin/bash

echo '
hello
there
'

echo '
Blah blah
Test
'

echo '
Try this command:

    $ fubar baz

'

echo '
Your program has been compiled successfully.
You can use "fubar" to run it:

    fubar baz

Run "fubar" for more commands.
'
```

<img width="377" alt="screen shot 2016-10-11 at 6 06 44 pm" src="https://cloud.githubusercontent.com/assets/2126073/19280573/73cd9d20-8fde-11e6-95c5-bedadcc91b0a.png">

**Comment by infertux** [comment]
@simonewebdesign Just pushed a new release that should fix this. `gem update bashcov` and you should be good to go :)
