### ISSUE TITLE
Use Bison for lexer?

### ISSUE THREAD

**Issue by infertux** [infertux/bashcov#25]
We're currently parsing multiline strings using [horrible regexpes](https://github.com/infertux/bashcov/blob/master/lib/bashcov/lexer.rb#L36-L55). I'd like to keep `lexer.rb` simple but it might be worth using [Bison](https://www.gnu.org/software/bison/) and the [BNF definition of the Bash grammar](http://bashcookbook.com/bashinfo/source/bash-2.05a/parse.y) next time we run into a regexp issue...

**Comment by tomeon** [comment]
Been playing around with FFI and https://github.com/mvdan/sh -- nothing beats Bash for parsing Bash, but `mvdan/sh` has a pretty slick interface that makes it easy to take a parse tree and turn it into a mapping of `lineno => relevant?`.  Will update again if/when I make any promising progress.

**Comment by infertux** [comment]
@tomeon https://github.com/mvdan/sh looks neat indeed. Perhaps Bashcov should be rewritten in Go and leverage it without FFI! Just (half) joking. Personally, I've been moving away from Ruby as you might have noticed, especially since I got addicted to [Elm](https://elm-lang.org/)...
