### ISSUE TITLE
Option to collect results cumulatively

### ISSUE THREAD

**Issue by lashd** [infertux/bashcov#28]
Hi,

First let me say thank you very much for this project. I didn't expect to find anything that would provide coverage for Bash.

I am working on a project that has a lot of legacy Bash scripts and very few tests. We want to be able wrap these scripts with 'black box' functional tests written in Ruby. In short, each RSpec example sets up some state then calls the described Bash script and subsequently makes assertions. Ruby invokes the test subject using Bashcov.

Therefore, as RSpec is in charge of running all tests and each test delegates to Bashcov, this means that coverage is essentially measured cumulatively. This wouldn't be a problem, however Bashcov's behaviour is to regenerate the coverage report after each invocation which results in the loss of anything that was previously captured.

Therefore...

I would like to be able to run Bashcov in a manner similar to:
`bashcov -a ./my_bash_script.sh`
or
`bashcov --append-results ./my_bash_script.sh`

This is doable and for now I have rigged up a solution which essentially provides an alternative to [bin/bashcov](https://github.com/infertux/bashcov/blob/master/bin/bashcov). This:
- intercepts the '-a' switch before passing the other command line arguments on to Bashcov as per normal
- Uses `SimpleCov::ResultMerger` instead of `SimpleCov::Result` to write the results
- Uses a unique command name, to avoid results being overwritten.

If you think that this feature would be useful, I would be happy to refine how it should work via a discussion in this ticket and submit a pull request with a proper implementation. That is as long as it's not to much work :)

Let me know your thoughts and thanks again.

**Comment by infertux** [comment]
Hi, I feel like what you're suggesting should be the default behaviour, hence no `-a` flag is needed IMO.

As for having unique command names, we could infer some unique string from the parent script such as the `$PPID` and/or the process name. We could also allow to customise it through some env variable, e.g. `SimpleCov.command_name Bashcov.fullname + (ENV['TEST_ENV_OR_WHATEVER'] || '')`.

Alternatively, you could wrap all scripts within a single one, similarly to https://github.com/infertux/bashcov/blob/master/spec/test_app/test_suite.sh but that might not be possible depending of your setup so I think having unique command names is a better solution.

Finally, replacing `SimpleCov::Result` with `SimpleCov::ResultMerger` should be quite easy :)

So yes this sounds like a great idea and I'd be happy to merge a PR as long as it doesn't break backward compatibility. Let me know if you need any help with that. Many thanks!

**Comment by infertux** [comment]
PS: https://github.com/colszowka/simplecov#merging-results should come in handy.

**Comment by Fatlog** [comment]
Hey, I'd be interested in this too (as per Issue #29 .
Is there a workaround in the meantime?

**Comment by infertux** [comment]
@lashd @Fatlog Release 1.8.0 is out. You can update with `gem update bashcov`.

This release supports merging multiple test runs. More information is available [here](https://github.com/infertux/bashcov#controlling-the-command-name).

Kudos to @BaxterStockman who did all the heavy lifting :)

Please reopen this issue if you're having any trouble.
