### ISSUE TITLE
Upgrade SimpleCov dependency to 0.9

### ISSUE THREAD

**Issue by infertux** [infertux/bashcov#3]

**Comment by rduplain** [comment]
Does this require anything other than changing the gemspec? I changed to `0.9.1` in a local checkout. All tests pass, and bashcov works as expected in my project.

```patch
-  gem.add_dependency 'simplecov', '~> 0.7.1'
+  gem.add_dependency 'simplecov', '~> 0.9.1'
```

I'm interested in this as I am exploring integration with coveralls, which depends on simplecov 0.9.1.

**Comment by infertux** [comment]
I assumed there would be potential breaking changes between 0.7 and 0.9 as per semantic versioning. I just skimmed through https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md and looks like nothing should impact Bashcov though. So I think it's all good :smile: 

Would you like to issue a pull request to update the Gemspec? Thanks!
