### ISSUE TITLE
Issues with multiline commands

### ISSUE THREAD

**Issue by AlexanderWillner** [infertux/bashcov#32]
Version: 1.6.0

Steps that will reproduce the problem?
1. Run ```git clone https://github.com/alexanderwillner/things.sh```
2. Run ```cd things.sh```
3. Run ```THINGSDB=test/Things.sqlite3 bashcov ./things.sh today```
4. Open ```coverage/index.html```

What is the expected result?
Coverage around a few percent.

What happens instead?
Coverage of ```81.09%```

Possible workaround:
Unknown.

Any additional information:
Needs ```sqlite```. Only tested on macOS.

**Comment by infertux** [comment]
Thanks for the nice bug report. It's probably picking up other Bash files in your working directory. You can instruct Bashcov to ignore them with the `--skip-uncovered` flag. Here's my result running `THINGSDB=test/Things.sqlite3 bashcov --skip-uncovered -- ./things.sh today`:

![2017-12-28-071504_1204x285_scrot](https://user-images.githubusercontent.com/345702/34403255-1e23f1bc-eb9f-11e7-894f-0fab05386917.png)

If you're still having issues, please update to the latest version with `gem update bashcov` and paste the output here.

**Comment by AlexanderWillner** [comment]
Thanks. I upgraded to version ```1.7.0```. However, now no output is generated anymore:
```
$ THINGSDB=test/Things.sqlite3 bashcov ./things.sh today ; file coverage
bashcov: warning: you are using a version of Bash that does not support BASH_XTRACEFD. All xtrace output will print to standard error, and your script's output on standard error will not be printed to the console.
Today Project|Today Todo
coverage: cannot open `coverage' (No such file or directory)
```

**Comment by infertux** [comment]
Your version of Bash is ancient and not supported. Bashcov requires at least Bash 4.2. I don't use OS X but you should be able to upgrade Bash with `brew`. I found [this](https://apple.stackexchange.com/questions/24632/is-it-safe-to-upgrade-bash-via-homebrew) if that helps.

You might need to tell Bashcov where Bash is located with `bashcov --bash-path=/path/to/bin ...`

**Comment by AlexanderWillner** [comment]
Seems to be something else.

Bult-in:
```
$ echo $BASH_VERSION; bashcov --version; THINGSDB=test/Things.sqlite3 bashcov ./things.sh today ; file coverage
3.2.57(1)-release
bashcov 1.7.0
bashcov: warning: you are using a version of Bash that does not support BASH_XTRACEFD. All xtrace output will print to standard error, and your script's output on standard error will not be printed to the console.
Today Project|Today Todo
coverage: cannot open `coverage' (No such file or directory)
```

New Bash:
```
$ echo $BASH_VERSION; bashcov --version; THINGSDB=test/Things.sqlite3 bashcov ./things.sh today ; file coverage
4.4.12(1)-release
bashcov 1.7.0
bashcov: warning: you are using a version of Bash that does not support BASH_XTRACEFD. All xtrace output will print to standard error, and your script's output on standard error will not be printed to the console.
Today Project|Today Todo
coverage: cannot open `coverage' (No such file or directory)
```


Built-in Bash with pointer to new Bash:
```
$ echo $BASH_VERSION; bashcov --version; THINGSDB=test/Things.sqlite3 bashcov --bash-path=/usr/local/bin/bash ./things.sh today ; file coverage
3.2.57(1)-release
bashcov 1.7.0
bashcov: warning: you are using a version of Bash that does not support BASH_XTRACEFD. All xtrace output will print to standard error, and your script's output on standard error will not be printed to the console.
Today Project|Today Todo
coverage: cannot open `coverage' (No such file or directory)
````

**Comment by infertux** [comment]
Weird, SimpleCov (the library used by Bashcov) is supposed to create the `coverage` directory automatically. Can you:

- check there is no permission issue with `mkdir coverage`
- check what version of SimpleCov you have with `gem query simplecov -l`

**Comment by AlexanderWillner** [comment]
No issue with ```mkdir coverage```.
Simplecov version:
```
$ gem query simplecov -l

*** LOCAL GEMS ***

simplecov (0.15.1)
simplecov-html (0.10.2)
```
Same issue at travis (executing ```bashcov shunit2 test/thingsTest.sh```): https://travis-ci.org/AlexanderWillner/things.sh/builds/322594996

**Comment by AlexanderWillner** [comment]
Actually, when I revert your change https://github.com/infertux/bashcov/commit/26177e0024bf89f01c6c2fd0dc603004dba03bb0 it works again. Well, besides that multiline variables are not recognised by the coverage tool.

**Comment by AlexanderWillner** [comment]
<img width="1391" alt="screen shot 2017-12-30 at 20 26 35" src="https://user-images.githubusercontent.com/307605/34456759-c98f0008-ed9f-11e7-9e58-993147ef88ce.png">

**Comment by infertux** [comment]
Can you try to update to the latest 1.8.0 release with `gem update bashcov` and let me know if you're still have issues? Thank you.

**Comment by AlexanderWillner** [comment]
Coverage report gets generated, thanks. However, the ```heredoc``` lines are still not recognised.

**Comment by infertux** [comment]
@AlexanderWillner Could you update to the latest 1.8.2 release with `gem update bashcov` - it should fix your heredoc issue. Please reopen this issue if not.

**Comment by AlexanderWillner** [comment]
lgtm - thanks!
