### ISSUE TITLE
Broken tests with SimpleCov 0.16+

### ISSUE THREAD

**Issue by infertux** [infertux/bashcov#36]
The [build is failing](https://travis-ci.org/infertux/bashcov/builds/356037192) with SimpleCov 0.16+. The coverage is now empty when using [SimpleCov::ResultMerger.results](https://github.com/infertux/bashcov/blob/master/features/step_definitions/bashcov_steps.rb#L23). I couldn't figure out why at first glance but it must be due to a change in [this diff](https://github.com/colszowka/simplecov/compare/v0.15.1...v0.16.1).

This seems to only affect feature tests and normal usage of Bashcov is working for me with SimpleCov 0.16.1.

**Comment by BaxterStockman** [comment]
@infertux -- I'll tack a crack at solving this in the next several days.

**Comment by infertux** [comment]
Blocked until https://github.com/colszowka/simplecov/pull/674 gets merged.
