### ISSUE TITLE
Executed bash thinks that bash-specific syntax is not supported

### ISSUE THREAD

**Issue by smspillaz** [infertux/bashcov#5]
Bash specific syntax is not supported in covered scripts, for instance, process substitution, e.g. `echo "data" > >(my_function))`

The reason for this is that bash's `argv[0]` is not "bash", but instead the environment variables prepended to it. This causes bash to drop back to sh-compatible mode.

**Comment by infertux** [comment]
Should be fixed in ca3c119bb7a5ce3eb5226bfaa7be5fbab9bc0643.
