### ISSUE TITLE
bashcov output should be silent by default

### ISSUE THREAD

**Issue by bje-** [infertux/bashcov#53]
`bashcov` produces output like this at the end of a run:

```
Run completed using bashcov 1.8.2 with Bash 4.4, Ruby 2.5.1, and SimpleCov 0.15.1.
Coverage report generated for /bin/bash script.sh ... etc ...
```

This output is sent to standard output which contaminates the output of the user's script and makes it difficult to use bashcov as part of a test harness. As the above output is not diagnostic in nature (that could be sent to standard error), I suggest that this output is suppressed by default but can be enabled with a `-v`/`--verbose` option.

**Comment by infertux** [comment]
I can easily remove the `Run completed [...]` line.

However the `Coverage report [...]` line is outputted by the [simplecov-html](https://github.com/colszowka/simplecov-html/blob/master/lib/simplecov-html.rb#L29) Gem. We can override it to a blank line (by monkey-patching `SimpleCov::Formatter::HTMLFormatter#output_message`) but removing it completely is more difficult.

Would it help your test harness if Bashcov only outputs an empty blank line (\n)?

**Comment by bje-** [comment]
No, because I don't want any output at all. I need to capture all output and match it against an expected value. A blank line could be removed by my test harness, sure, but I won't know whether `bashcov` or the program under test generated it.

**Comment by bje-** [comment]
This doesn't fix the issue, unfortunately. Now, to silence bashcov's own output, I have to use `-m`, which mutes the program under test as well!
