### ISSUE TITLE
`--bash-path` is not respected for `BASH_VERSION` detection

### ISSUE THREAD

**Issue by MPLew-is** [infertux/bashcov#57]
[`BASH_VERSION` is computed before taking into account the `--bash-path` argument](https://github.com/infertux/bashcov/blob/234a5a75112c37e5e964ee05c29ec5a3d4384d4d/lib/bashcov.rb#L149), meaning that the bash version will be detected based on `/bin/bash` rather than the path passed in.

As an example use case, I'm trying to get coverage working on macOS while not clobbering `stderr`; I installed Bash 5 via Homebrew, but `bashcov` still thinks I'm using the system version even when I pass the `--bash-path` argument in.

I tried to patch in a workaround, but I'm pretty much brand new to ruby and was still seeing some "instrumentation" output (though not all) print to `stderr`; I'll continue to work on it a little, but any pointers you might have would be helpful.

**Comment by abathur** [comment]
Ah! Glad to see this. I ran into this but assumed the flag wasn't even working.
