### ISSUE TITLE
[question] bash 'compiler'

### ISSUE THREAD

**Issue by hrpatel** [infertux/bashcov#60]
Hello,

We maintain a shell 'standard library' that we use across our projects: https://github.com/sdelements/shtdlib/blob/master/shtdlib.sh

If a script sources `shtdlib.sh`, would it be possible to use `bashcov` to determine which functions of `shtdlib.sh` were used and export/write those functions to a file? 

E.g. the script below would generate a smaller file that only contains the `debug`, `assert` and `color_echo` (called from `debug` and `assert`) functions. 

```bash
# Import the shell standard library
source /bin/shtdlib.sh

debug 10 "Running as ${UID:-$(id -u)}"

assert test -d "${script_dir}/build"
assert test -d "${script_dir}/dist"
```

**Comment by infertux** [comment]
That would be nice indeed, I looked into it a while back but couldn't find anything in Bash to implement this feature sadly.
