### ISSUE TITLE
Are you planning a new release?

### ISSUE THREAD

**Issue by ddidier** [infertux/bashcov#63]
Hi,
The `simplecov` version is set to `0.15.1` in `bashcov` `1.8.2`. I'd like to use a more recent version. Are you planning a new release with the dependencies updates?

**Comment by infertux** [comment]
Apologies for the delay. Life got in the way. A new release is well overdue indeed, I'll try to push one to rubygems.org over the next few days.

**Comment by ale5000-git** [comment]
Hi, I have try to look at rubygems.org but I don't see anything new.
Does something happened?

Thanks in advance.

**Comment by infertux** [comment]
Bashcov 3.0 has finally been released! It includes a bunch of bug fixes and dependency updates. Thank you all for your patience. You can update it with `gem update bashcov` or `gem 'bashcov', '~> 3.0'` in your Gemfile.

> Hi, I have try to look at rubygems.org but I don't see anything new.
> Does something happened?

To be frank, lack of funding. Upgrading Bashcov to run with Ruby 3 and newer versions of Bash took hundreds of hours of work. It's hard to find time for it when there is zero incentive. I created Bashcov over a decade ago when I was a student with basically no responsibilities but things have changed now. I need to prioritize work that puts food on the table. Receiving even a few dollars a month would mean Bashcov has actual value to some people and it would allow me to spend more time on it. I added a [Sponsorship](https://github.com/infertux/bashcov#sponsorship) section in the README to raise awareness. In the meantime, Bashcov will be maintained on a "best effort" basis which isn't ideal for anyone involved but it's the reality of too many open-source software out there.

If you use Bashcov professionally, please considerer supporting it on [Liberapay](https://liberapay.com/infertux) through your employer or directly.  Thank you for supporting *Free and Open-Source Software*.
