### ISSUE TITLE
Function definition line missed

### ISSUE THREAD

**Issue by samlikins** [infertux/bashcov#70]
I'm using bashcov on a project and have nearly 100% coverage.  The only lines not reported as covered of known executed code are the function names.  After running unit-tests (using shunit2) with bashcov and the report generated, the following line is output:
```bash
Run completed using bashcov 1.8.2 with Bash 5.1, Ruby 3.1.2, and SimpleCov 0.15.1.
```
The HTML report specifies the following:
```html
Generated by simplecov v0.15.1 and simplecov-html v0.10.2
```

I'm not sure if this is an issue with bashcov or simplecov,  I have a strong suspicion that the issue involves the characters used in the function names; though the characters are valid in BASH.  Bellow are examples of the function names that aren't registering as covered:
```bash
ansi::es() {
    # ...
}
ansi::nc() {
    # ...
}
```
Though, when modifying the function definitions to use the `function` keyword as below:
```bash
function ansi::es {
    # ...
}
function ansi::nc() {
    # ...
}
```
The definition lines are not listed as missed, just as the other functions not named with colons.

As there is a workaround with the naming in this format, this is not a show-stopper, but this is an issue that should be corrected.

**Comment by infertux** [comment]
Thank you for the nice bug report, Bashcov expects `[a-z]` in the function names indeed. Let me fix it...

**Comment by infertux** [comment]
Turns out colons in function names are not allowed according to Bash documentation but they work just fine in practice: https://unix.stackexchange.com/questions/463560/bash-script-function-names-containing-double-colon

I'm gonna release Bashcov 3.0.2 with that fix shortly.

**Comment by infertux** [comment]
@samlikins https://rubygems.org/gems/bashcov/versions/3.0.2

**Comment by samlikins** [comment]
@infertux, thank you for your efforts.  I've removed my workarounds and reran the coverage with no adverse results.  Your patch has worked!
