### ISSUE TITLE
Latest release April 2023 No longer has any coverage in report

### ISSUE THREAD

**Issue by animaxcg** [infertux/bashcov#71]
the latest release no longer finds any coverage on scripts at all. If this is a change in setup needed that needs to be documented:
repo steps on macos with `Run completed using bashcov 3.0.2 with Bash 3.2, Ruby 3.0.0, and SimpleCov 0.21.2`:
hello.sh:
```
#!/bin/bash
echo "hello"
```

```
bash-3.2$ bashcov hello.sh 
+BASHCOV>4a74ab0b-0f09-46b7-b474-2fc705aaea0024a74ab0b-0f09-46b7-b474-2fc705aaea00hello.sh4a74ab0b-set -x
+BASHCOV>4a74ab0b-0f09-46b7-b474-2fc705aaea0034a74ab0b-0f09-46b7-b474-2fc705aaea00hello.sh4a74ab0b-echo hello
hello
Run completed using bashcov 3.0.2 with Bash 3.2, Ruby 3.0.0, and SimpleCov 0.21.2
Coverage report generated for /bin/bash hello.sh to /Users/joehale/projects/hel/coverage. 0 / 2 LOC (0.0%) covered.
```

Previous versions would return 100% coverage

**Comment by infertux** [comment]
You're running Bash 3.2 which is [no longer supported](https://github.com/infertux/bashcov/blob/master/CHANGELOG.md#v300-2023-04-10-changes) since Bashcov 3.0. I don't use macOS but I believe you can install a recent version of Bash with [Homebrew](https://brew.sh/).
