### ISSUE TITLE
CI with GitHub Actions?

### ISSUE THREAD

**Issue by tomeon** [infertux/bashcov#75]
Would you be interested in a PR introducing support for GitHub actions (and replacing GitLab CI)?  I for one would find it handy to have CI run for PRs and see the results in the PR page.  Helpful for when I inevitably do something boneheaded like forget to run RuboCop... :)

**Comment by infertux** [comment]
Sure, please go ahead. I've been using GitLab CI because I'm more familiar with it but would love to have GitHub actions support. I don't think we need to drop GitLab CI though as both could run in parallel and not interfere with each others.
