### ISSUE TITLE
example doesn't have 100% coverage

### ISSUE THREAD

**Issue by tooptoop4** [infertux/bashcov#81]
i followed below link and expected to get 100% coverage for example.sh

https://listed.zygoon.pl/17659/introduction-to-bashunit-unit-testing-for-bash-scripts

but result was just 33% coverage

**Comment by infertux** [comment]
Looks like you're using another `bashcov`: https://github.com/zyga/bashcov

**Comment by tooptoop4** [comment]
i'm using this one, just the example shells from the blog
