### ISSUE TITLE
Conflict with codecov

### ISSUE THREAD

**Issue by ale5000-git** [infertux/bashcov#88]
I use bashcov with codecov formatter and I get this:
`Warning: Error occurred while trying to load .simplecov. Error message: Unable to activate codecov-0.6.0, because simplecov-0.22.0 conflicts with simplecov (>= 0.15, < 0.22)`

Could you please allow both version of simplecov?
- 0.22.0
- 0.21.2

**Comment by infertux** [comment]
Please run `bundle update bashcov` (or `gem update bashcov`) to install Bashcov version 3.1.3 which should fix this issue.
