### ISSUE TITLE
【question】Hello, If the shell script is a resident process, like 'while loop,daemon' ,Does bashcov support it? or Can I set timeout in bashcov?

### ISSUE THREAD

**Issue by yadonglian** [infertux/bashcov#90]
![image](https://github.com/user-attachments/assets/022384d0-e7b5-47c1-bea6-57fc509a5a61)
like this,

**Comment by tomeon** [comment]
@yadonglian 

> If the shell script is a resident process, like 'while loop,daemon' ,Does bashcov support it?

Not sure I fully understand the question, but I believe the answer is "sort of".  Bashcov can collect coverage statistics for such processes, but will only write them out once the processes exit (or, rather, once the command provided to Bashcov exits).

> Can I set timeout in bashcov?

No, but you can write a wrapper script that enforces a timeout and then run **that** script with Bashcov:

```sh
#!/usr/bin/env bash

exec timeout 10s ./the/real/shell/script
```

```shell-session
$ bashcov -- ./the/timeout/wrapper
```

**Comment by yadonglian** [comment]
Thanks, I see。The script must have an exit before Bashcov collects coverage reports
